### ISSUE TITLE
Help Needed for Updating Domains Count

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#145]
@hagezi I am trying to update the README.md file table with the latest domain count. Here is the table:
| Syntax | Domains/Entries |
| --- |:---:|
| [Adblock Plus](https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/adblock.txt) | 2000 |
| [Domains](https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/domains.txt) | 4000 |

How did you manage to update the value in your repo automatically?

**Comment by hagezi** [comment]
You have to copy the readme, a source for the github readme. In this source, you assign placeholders for the numbers.
E.g. `cnt_abp` and `cnt_domains`. At the end of your build, you replace these placeholders with the actual number using `sed`.

**Comment by jarelllama** [comment]
do you have a sample code of how you assign the placeholders to the correct line and position in the README.md file?

**Comment by jarelllama** [comment]
Finally got code that works. Although I don't think it's the best option:
```
#!/bin/bash

readme="README.md"
domains_file="domains.txt"
adblock_file="adblock.txt"

# Get line numbers

adblock_line_num=$(cat README.md | grep -n "| \[Adblock Plus\](https://raw" | cut -d ":" -f 1)

domains_line_num=$(cat README.md | grep -n "| \[Domains\](https://raw" | cut -d ":" -f 1)

grep -vE '^(!|$)' "$adblock_file" > adblock.tmp

grep -vE '^(#|$)' "$domains_file" > domains.tmp

adblock_count=$(wc -l < adblock.tmp)

domains_count=$(wc -l < domains.tmp)

# Replace numbers with four or more digits with  the new counts

sed -i "${adblock_line_num}s/[0-9]\{4,\}/$adblock_count/" "$readme"

sed -i "${domains_line_num}s/[0-9]\{4,\}/$domains_count/" "$readme"

rm *.tmp
```

**Comment by hagezi** [comment]
You can also do it this way, but it is actually quite simple, you just have to create a copy of the readme locally, this will then always be the basis for any changes. This means that if you want to make changes to the readme, then only in the "copy". In this copy you insert the placeholders for the count. At the end of your build process, you replace the placeholders with the count and copy the base file as README.md into your repository. Your README.md in the repository is thus "generated" with every build.
This is how I do it.

**Comment by jarelllama** [comment]
do you insert the placeholders for the count manually by hand? or do you have a script that replaces the old count with the placeholder?

**Comment by hagezi** [comment]
> do you insert the placeholders for the count manually by hand? or do you have a script that replaces the old count with the placeholder?

There is no count in the base readme, only the placeholders, which I insert once and replace with each build. The copy with the placeholders ALWAYS serves as the basis. This means that I can only make changes in the README.md in my base readme, because it is overwritten with every build.
