### ISSUE TITLE
merge other toplists

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#151]

**Comment by jarelllama** [comment]
@hagezi would you recommend me to use your `toplist-merge.txt`?

**Comment by hagezi** [comment]
No, it is Umbrella, Tranco + Chrome. Use Umbrella only.

**Comment by jarelllama** [comment]
is there a reason the other lists shouldn't be used?

**Comment by hagezi** [comment]
Yes, they include some fake, crap, scam and malware domains. I use the merged list only for extracting subdomains.

**Comment by jarelllama** [comment]
Ah I see. thank you.
