### ISSUE TITLE
Advice on How to Move Forward

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#232]
@hagezi @durablenapkin @iam-py-test @bongochong
Tagging some list maintainers for advice.

I've been studying the scam domains my script extracts and what I'm seeing very often is a domain with a wildcard DNS record with a random subdomain like `jlksjd.soudkydubove.cz`. The ABP list could of course block all subdomains but the Domains list would have to block every subdomain to be effective.

I made a testing script that uses this search query URL: `https://www.google.com/search?q=site:${term}...` As you can see it uses the `site:` parameter to search for all indexed subdomains of these wildcard domains.

Here's a snippet of the output:
```
worldwebworks.cz
Domains retrieved: 100
--------------------------------------
perfectmask.pl
Domains retrieved: 100
--------------------------------------
telemedicine-solutions.com
Domains retrieved: 100
--------------------------------------
soudkydubove.cz
Domains retrieved: 100
--------------------------------------
perfectmask.pl
Domains retrieved: 100
--------------------------------------
```

From the results you can see each search query retrieves the maximum (100) number of subdomains... Adding all these subdomains to the Domains list would greatly inflate the list size. Just a few of the retrieved subdomains increased the list size to over 10000 domains.

I'm not quite sure how to proceed after knowing these facts. The Domains list has been very frustrating to maintain (the [add_subdomains.sh](https://github.com/jarelllama/Scam-Blocklist/blob/main/workflow_scripts/add_subdomains.sh) script took days to write and test) and now I'm thinking if it is worth the effort or if I should just stick to supporting only formats that allow for wildcard blocking, especially since Pihole now supports ABP.

I have also thought of creating an Extended Domains list that includes these subdomains. It would be much bigger than the current Domains list and would definitely take a lot of new code and effort to maintain. I'm not really excited about doing that.

I would appreciate any help or feedback.

**Comment by jarelllama** [comment]
For context, this is the current process for the Domains list:

>### Subdomains
>
>Common subdomains are added to domains with no [wildcard record](https://developers.cloudflare.com/dns/manage-dns-records/reference/wildcard-dns-records/). See the list of subdomains checked here: [subdomains.txt](https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/data/subdomains.txt)
>
>Only the `www` and `m` subdomains are added to domains with wildcard records so as to not inflate the blocklist size.
>
>Subdomains are only added if they are resolving (in the case of domains with wildcard records, all subdomains resolve).

**Comment by hagezi** [comment]
From my point of view, it makes zero sense to fill lists with subdomains that are randomly generated. These usually don't have a long lifespan either.

So my opinion is, don't inflate the lists with possible subdomains. Current blockers support either pure wildcard domain lists without subdomains or the AdBlock format. Blockers that only support hosts are of course no longer supported. But ad blockers that still can't do wildcard blocking in 2023, tough luck.

If the clamour wasn't so great, I would also discontinue support for hosts/domains/subdomains on my lists. For some lists where it makes no sense to add thousands of subdomains (such as DynDNS), I have already done so.
The fuss of searching for and adding possible subdomains - you don't get them all anyway - would be eliminated and the handling of the lists would be much simpler.
Stephan @sjhgvr tried it back then and got a lot of criticism, but on the plus side, Pi-hole now supports the AdBlock format.

**Comment by jarelllama** [comment]
> For some lists where it makes no sense to add thousands of subdomains (such as DynDNS), I have already done so.

I have noticed you removed support for domains/subdomains for your Fake list too. It was what made me consider dropping support for my Domains list too especially with the amount of code it takes to add possible subdomains (many of which are missed).

If I do end up dropping the Domains list I will be sure to make another announcement at least a week in advance. I will wait for further advice/feedback before I make any decision.

**Comment by sjhgvr** [comment]
https://www.reddit.com/r/oisd_blocklist/comments/11s6dov/

**Comment by bongochong** [comment]
I don't think there's any harm in leaving the process as is, while letting users know on your readme files that the unoptimized lists will not provide the same comprehensive coverage which your TLD-compressed lists do. I've run into this conundrum a lot with my larger list and it was a primary impetus for my introduction of mini / light versions. Hundreds of subdomain variations are not uncommon with scam or malware servers and it can be frustrating to deal with that. Just take a look at the bottom half of my [PAC file template](https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/BLT/parsing/pactemplate.txt) and you'll see how repetitive these subdomains can be. If you do completely move over to TLD-compressed lists, remember to generate a plain version of them, which is basically your ABP list without any syntax or comments. Software like [PersonalDNSFilter](https://github.com/IngoZenz/personaldnsfilter), and ad-blocking plugins on OpenWrt prefer this. You're doing good work, so don't feel too stressed about whatever road you decide to take here :^)

**Comment by bongochong** [comment]
P.S. Forgot to mention that I agree with hagezi's suggestion not to worry about adding subdomains which your scripts haven't already captured (though arguments can be made for adding `www` in unoptimized lists when necessary). The amount of scam domains out there is already huge, and oftentimes blocking the topmost level domain will hamper the intended function of related subdomains on the user's end, even if they're only using a hosts file.

**Comment by jarelllama** [comment]
Thanks everyone for the help :)
I have decided to drop support for the Domains list. This way there's a lot less code to maintain since I don't have to worry about adding subdomains.

With this increased flexibility, I will try introduce new list formats like Unbound, DNSMasq and Wildcard Domains. I will update in a separate issue if there is any major changes to note! Thanks to everyone again for the support.
