### ISSUE TITLE
Add base domains for light list

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#259]

**Comment by iam-py-test** [comment]
Out of curiosity, would you mind explaining what domains are excluded from this list version?
Thanks

**Comment by jarelllama** [comment]
Hi @iam-py-test . I've been making changes very actively recently so I am waiting for everything to stabilize for at least a week before making any announcements.

But since you asked, I have added new sources to the blocklist which has greatly inflated the number of entries. I understand some list maintainers are cautious about the list sizes so I created a light version. Here is the excerpt from the updated README:

## Light version
Targeted at list maintainers, a light version of the blocklist is available in the [lists](https://github.com/jarelllama/Scam-Blocklist/tree/main/lists) directory.

<details>
<summary>Details about the light version</summary>
<ul>
<li>Intended for collated blocklists cautious about size</li>
<li>Does not use sources whose domains cannot be filtered by date added</li>
<li>Only retrieves domains added in the last month by their respective sources (this is not the same as the domain registration date), whereas the full blocklist includes domains added from 2 months back and onwards</li>
<li>! Dead domains that become alive again are not added back to the blocklist (due to limitations in the way the dead domains are recorded)</li>
</ul>
Sources excluded from the light version are marked in SOURCES.md.
<br>
<br>
Total domains: 1988
</details>

**Comment by iam-py-test** [comment]
Thanks
