### ISSUE TITLE
Implement regex matching

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#295]

**Comment by jarelllama** [comment]
Initial testing with the NRD feed went well. No false positives along with high detection rate using a very generic regex pattern.

![image](https://github.com/jarelllama/Scam-Blocklist/assets/91372088/63e29cf9-11e5-4b1d-a897-fa22ac8e4e95)

@iam-py-test do you foresee any issues with such a detection method against an NRD feed?

**Comment by jarelllama** [comment]
NRDs matched: [results.txt](https://github.com/jarelllama/Scam-Blocklist/files/14957520/results.txt)

**Comment by hagezi** [comment]
Looks good, great work.

**Comment by iam-py-test** [comment]
Agreed.

**Comment by jarelllama** [comment]
Thanks everyone for the support! @hagezi note that the regex matching source will only be used for the full blocklist because of the number of domains it brings in.

**Comment by jarelllama** [comment]
Feel free to recommend any sites often targeted by phishing/cybersquatting attacks.
