### ISSUE TITLE
Automated NSFW Detection

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#308]
Just trying to read the room, @sjhgvr @sefinek24 would you be interested in a NSFW blocklist built using the same regex matching I use to detect phishing NRDs?

I am unable to use the Google Search source because of the limited API calls per day, but regex matching seems to be effective:

Sample 50 NSFW NRDs found:
``` console
bestporn-games.com
omegaporn.net
0culuspornation.com
0lgayporn.com
0porno.click
1004porn.com
10kporn.com
11porn.com
123-porno.mobi
123pornoxxx.info
125porn.xyz
18amateurporn.com
18japanporn.mobi
18javporn.com
18porn.co
18porn.info
18porn.vg
18pornhd.xyz
18teenagersporn.com
18teenporno.info
18teenpornotv.com
18xnxxporn.com
18xvideoporn.best
18xxxvideoporn.com
18youngpornhd.online
1banglaporn.com
1bengaliporn.com
1bhabhiporn.com
1bollywoodporn.com
1deshiporn.com
1gigporno.online
1hindiporn.com
1indianhdporn.com
1indianpornhd.com
1indianpornsites.com
1indianpornvedios.com
1indianpornvideo.com
1malayalamporn.com
1malluporn.com
1nepaliporn.com
1pakistaniporn.com
1porn.club
1porn.net
1porn.xyz
1porngifs.com
1pornindian.com
1punjabiporn.com
1stpornafrica.com
1tamilporn.com
1winporn.com
```

**Comment by jarelllama** [comment]
A more logical implementation would be to use the Tranco toplist to find NSFW sites in, not just the NRD feed.

**Comment by jarelllama** [comment]
My bad, I got a little carried away...

Here is the blocklist only available in ABP syntax:
https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/adblock/nsfw.txt

* Domains are automatically retrieved from the Tranco Top Sites Ranking daily
* Dead domains are removed daily
* Note that resurrected domains are not added back into the blocklist
* Note that parked domains are not checked for in this blocklist

Currently has 830 domains not found in the oisd NSFW list:
``` console
$ comm -23 nsfw.txt oisd_nsfw.txt | wc -l
830
```

@iam-py-test you might be interested too.

**Comment by sjhgvr** [comment]
I'll add it to the list of oisd nsfw sources and let my script check the domains/sites for nsfw-ness.
Thanks

**Comment by jarelllama** [comment]
Thanks @iam-py-test

**Comment by sefinek24** [comment]
Alright, if the NSFW list is added to OISD NSFW, I won't implement it on my end due to duplicates

**Comment by sjhgvr** [comment]
> Alright, if the NSFW list will be added to OISD NSFW, I won't implement it on my end due to duplicates https://blocklist.sefinek.net/generated/v1/0.0.0.0/porn/oisd/nsfw.fork.txt

You know thats a hosts-syntax file without any "www."-prefixed domain right?

**Comment by sefinek24** [comment]
Nah, so I will have to add it after all. I didn't know that 😆

**Comment by sjhgvr** [comment]
> Nah, so I will have to add it after all. I didn't know that 😆

And even if you do that what about subdomains? Known/unknown.. etc ..
Read about why I ditched hosts-format on the frontpage of https://oisd.nl/

**Comment by jarelllama** [comment]
@sefinek24 for your Pihole lists you can use the ABP format to block wildcards.

Anyway, closing this issue now.
