### ISSUE TITLE
Considering switching ABP syntax to ||example.com^$all

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#310]
I recently noticed https://github.com/durablenapkin/scamblocklist switched to ||example.com^$all for all rules. (Thanks @durablenapkin).

This made me curious and went to read https://adguard.com/kb/general/ad-filtering/create-own-filters/ again.

>By default, such rules do not work for document requests. This means that the ||example.org^ rule will block a request made to example.org when you try to navigate to this domain from another website, but if you type example.org into the address bar and try to navigate to it, the website will open. To block the document request, you will need to use a rule with the [$document modifier](https://adguard.com/kb/general/ad-filtering/create-own-filters/#document-modifier): ||example.org^$document.

I tested this with the AdGuard AdBlocker extension on Firefox and indeed ||example.com^ still lets the page load when navigating straight from the address bar, where as ||example.com^$all did not.

||example.com^$all:
![image](https://github.com/jarelllama/Scam-Blocklist/assets/91372088/0bc744bb-e66c-4b58-9551-488c259085ad)

||example.com^:
![image](https://github.com/jarelllama/Scam-Blocklist/assets/91372088/241307b9-0e6d-415c-9839-154c982b9ab0)

I'm considering appending all rules in adblock.txt with $all now considering it's not uncommon for scam victims to key in the URL directly.

@hagezi what do you think?

**Comment by hagezi** [comment]
Useful for browser content blockers, but this also cancels the compatibility for Pi-hole. Without having tested it, only rules in the form `||example.com^` without modifiers are processed there.

**Comment by hagezi** [comment]
This does not seem to be a problem in uBlock:

![grafik](https://github.com/jarelllama/Scam-Blocklist/assets/104343908/3f54ecfa-7a79-42b3-8f08-312bd0ebd987)

**Comment by jarelllama** [comment]
Indeed both with and without the $all modifier works on uBlock.

@sjhgvr do you know if modifiers break Pihole compatibility?

**Comment by jarelllama** [comment]
From https://pi-hole.net/blog/2023/03/22/pi-hole-ftl-v5-22-web-v5-19-and-core-v5-16-1-released/#page-content:
> To be precise, we have added support for the following domain matching syntax defined [here](https://adblockplus.org/filter-cheatsheet#blocking2) at the time of release. No other filter rules on that page are appropriate for a DNS-based blocker, and so any entries matching them will be ignored.

So yes, I suspect too that having modifers would break Pihole. Seems safer to keep the current syntax.

**Comment by jarelllama** [comment]
> In addition to Pi-hole, there are also other DNS blockers that support AdBlock. I think that these would also be affected.
> 
> If I have understood you correctly, does the "problem" only occur with AdGuard?

I only did the quick test on uBlock and the AdGuard extensions. With only AdGuard needing the $all modifier

**Comment by jarelllama** [comment]
I'm not sure if I should create a separate list with and without the modifiers. Seems redundant considering most maintainers integrating my lists strip modifiers off.

**Comment by durablenapkin** [comment]
> So yes, I suspect too that having modifers would mean the entire rule is ignored in Pihole. Seems safer to keep the current syntax.

Thanks for this, I'll remove the `$all` modifiers. After looking into it further OISD's ABP lists don't have modifiers.

**Comment by hagezi** [comment]
AdBlock Plus does not seem to recognise the $all modifier, only $document.

What a mess, I would stick with the "DNS syntax".

**Comment by jarelllama** [comment]
Thanks for looking into it @hagezi
