### ISSUE TITLE
Scam Webinar from YT Ads

### ISSUE THREAD

**Issue by xRuffKez** [jarelllama/Scam-Blocklist#324]
### What domains should be blocked?

kindlepublishingincome.com

### Why should they be blocked?

Obviously Scam to grab users data and offering a webinar which you need to pay to be "very successful" in publishing ebooks.

**Comment by jarelllama** [comment]
Thank you for this.

**Comment by jarelllama** [comment]
My bad, I checked through again and it appears mostly as an eBook. The sites related to its search term are merely bookstores. Hard to determine if it is truly a scam or not. Will remove for now.
