### ISSUE TITLE
GeT fReE rObUx Scam from YT Ads

### ISSUE THREAD

**Issue by xRuffKez** [jarelllama/Scam-Blocklist#325]
### What domains should be blocked?

stargamingpro.com

### Why should they be blocked?

Exact URL: https://stargamingpro.com/get+robux

**Comment by jarelllama** [comment]
Sorry, the page you linked to is not found. And the site itself has no proof of being malicious.

**Comment by xRuffKez** [comment]
Okay, they put down the link then
