### ISSUE TITLE
Integrate Emerging Threats source

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#333]
- [x] Extract domains from feed
- [x] Determine if the number of domains is practical 
- [x] Check number of NRDs present 
- [x] Check scope of domains (how many are phishing compared to malware?)

**Comment by jarelllama** [comment]
Categories: https://community.emergingthreats.net/t/current-suricata-5-and-suricata-6-rule-categories/94

**Comment by jarelllama** [comment]
Domains found in DNS rules:
emerging-phishing.rules: 634
emerging-malware.rules: 5188

Will add phishing to the blocklist, including light. 
Malware is too big and out of scope for this project. Will consider forking https://github.com/tweedge/emerging-threats-pihole

**Comment by jarelllama** [comment]
Categories of interests for malicious:
* Adware-PUP–This category is for signatures to identify software that is used for ad tracking or other types of spyware related activity which is often undesirable. Note: this category is present in rulesets for Suricata 5.0 or later. In Suricata versions prior to 5.0 and Snort 2.9 these rules are in the Malware category.
* Malware–This category is for signatures to detect malicious software. Rules in this category detect activity related to malicious software that is detected on the network including malware in transit, active malware, malware infections, malware attacks, and updating of malware. This is also a highly important category and its highly recommended to be run. Note: this category is present in rulesets for Suricata 5.0 or later. In Suricata prior to 5.0 and Snort 2.9 these rules are in the Trojan category.
* Mobile Malware–This category is for signatures that indicate malware that is associated with mobile and tablet operating systems like Google Android, Apple iOS, and others. Malware that is detected and is associated with mobile operating systems will generally be placed in this category rather than the standard categories like Malware.
* Phishing–This category is for signatures which detect credential phishing activity. This includes landing pages exhibiting credential phishing as well as successful submission of credentials into credential phishing sites. Note: this category is present in rulesets for Suricata 5.0 or later. In Suricata prior to 5.0 and Snort 2.9 these rules are in the Current Events category.

**Comment by jarelllama** [comment]
@hagezi, was there a reason you removed https://github.com/tweedge/emerging-threats-pihole from TIF?

**Comment by hagezi** [comment]
I suspect it's because it hasn't been updated for a while, but I can't remember exactly. In any case, it fell victim to a clean-up operation.

**Comment by jarelllama** [comment]
I also assumed it hasn't bee updated because of the lack of commits, but apparently workflows has been updating the blocklist daily.
