### ISSUE TITLE
Blocklist checker

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#335]
Hi @hagezi, I want to make a simple script to automatically check blocklists with a workflow and perhaps integrate it into a GitHub Action.

Here are the things I could possibly check for:
* Number of non-comment entries
* Unicode
* Invalid entries
* Number of dead domains
* Number/domains in Tranco
* Number of domains covered by other blocklists

Do you have any suggestions for what else I could check?

**Comment by hagezi** [comment]
Sounds good, I can't think of any other options at the moment.

**Comment by jarelllama** [comment]
Up at https://github.com/jarelllama/Blocklist-Checker
