### ISSUE TITLE
newtoki(xxx) and toonkor(xxx) are false positives

### ISSUE THREAD

**Issue by t3stikl3s** [jarelllama/Scam-Blocklist#371]
In your list, newtoki337.com and toonkor349.com are blocked.

They are Korean websites used to read web comics and are not inherently scam/phishing sites.

They are regularly refreshed due to their less than legal nature hence the (xxx) part in the title as the numbers regularly change.

**Comment by jarelllama** [comment]
Thank you for reporting. All lists have been updated.
