### ISSUE TITLE
Phish

### ISSUE THREAD

**Issue by xRuffKez** [jarelllama/Scam-Blocklist#376]
### What domains should be blocked?

meritserve.cfd

### Why should they be blocked?

https://meritserve[.]cfd/139adde6734b2de630f903599974ec97

**Comment by jarelllama** [comment]
Can't seem to access it

**Comment by xRuffKez** [comment]
They randomize the url so it's harder to investigate

**Comment by xRuffKez** [comment]
https://dnschecker.org/#A/meritserve.cfd
