### ISSUE TITLE
Report domains 

### ISSUE THREAD

**Issue by FakesiteListHUN** [jarelllama/Scam-Blocklist#381]
Hello

I am also make a scam blocklist fraudulent online stores that primarily target Hungarian users, I thought you might add it to your own list.
[Raw link](https://raw.githubusercontent.com/FakesiteListHUN/FakeWebshopListHUN/refs/heads/main/fakewebshoplist)
[Repo link](https://github.com/FakesiteListHUN/FakeWebshopListHUN)

**Comment by jarelllama** [comment]
Thanks. I will continue to monitor for a few days.

**Comment by jarelllama** [comment]
```
Source: FakeWebshopListHUN
Raw: 124  Final: 118  Whitelisted:   0  Excluded:   0  Toplist:   5
Processing time: 1 second(s)
----------------------------------------------------------------------
Entries requiring manual review:
bazarulonline.ro (toplist)
lilipretty.com (toplist)
sepa.hu (toplist)
szerszamkell.hu (toplist)
zinubyy.com (toplist)
```

**Comment by jarelllama** [comment]
Domains added: 3365

Suspected false positives (20):
```
altroconsumo.it
bazarulonline.ro
elerhetootthon.hu
euro-markt.hu
flickr.com
gizzmo.hu
hs-plus.com
outdoorproject.com
obiono.com
paypal-community.com
portaldaqueixa.com
rareconnect.org
rocketreach.co
sayabling.com
sepa.hu
soldius.com
uzo.com
toprabat.hu
vigorshop.hu
zendesk.com
```

**Comment by FakesiteListHUN** [comment]
Thank you, yes there is some problem on my list (maybe my script just scrape too much).
Of course flickr and paypal-community is false positive, I'll correct it.

Public negative reviews:
[elerhetootthon.hu](https://www.olcsobbat.hu/boltok/elerheto_otthon/)
[euro-markt.hu](https://www.trustpilot.com/review/euro-markt.hu)
[portaldaqueixa.com](https://www.trustpilot.com/review/portaldaqueixa.com)
[vigorshop.hu](https://www.olcsobbat.hu/boltok/vigorshop_hu/)

obiono.com and sayabling.com are part of the Wisteria Trade Limited company [malwaretips.com link](https://malwaretips.com/blogs/wisteria-trade-limited/)
"HS Plus doo" company offer cheaply made product (we have victims our facebook group) these sites belongs to them:
hs-plus.com
soldius.com
toprabat.hu

**Comment by jarelllama** [comment]
Thank you. I'll look into it.
