### ISSUE TITLE
Potential Domain Generation Algorithm List

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#390]
Hi @hagezi @xRuffKez, I am using https://github.com/exp0se/dga_detector to detect DGA NRDs (using xRuffKez NRD feed).

DGA Detector uses the following factors for DGA detection:
```
    entropy - High entropy is another indicator of DGA domain. Threshold is 3.8
    consonants - High consonants count is an indicator of DGA domain. Threshold is 7
    length - High domain length can also indicate DGA. Threshold is 12.
```

The process I am testing is as follows:
- Keep only domains longer than 15 characters from NRD feed (to reduce runtime and potential false positives)
- Download English word list from https://github.com/dwyl/english-words
- Keep only words longer than 3 characters from word list (so TLDs like .com don't get matched)
- Remove domains in the updated NRD feed that contain words from the updated word list (since DGA domains seem to more random and include less actual words)
- Run DGA Detector on the filtered domains

The problem I am facing is that even with all the filtering above, I am still getting about 87986 domains retrieved. Meaning on the first run of this new source, the blocklist would be increased to 271,245 domains.
This number can reduced by increasing the minimum character amount from the NRD feed. For example, including only domains longer than 17 characters yields 61930 domains.

@hagezi I would like to hear your thoughts.

Here is a sample of the results:

``` shell
$ shuf -n 50 results.tmp
vrwmpqdqdzmqzqq.top
67645c62-baf9-40bb-b6ac-2676ffd7cebc.com
xn----7sbbc6bknder.xn
najlepszaimpreza.com
dmis-amc-gov-af.com
xn--1lqq7i0z6b104a.com
c0f1c33b-151e-43e5-8e05-4ae578c178d7.com
smkpgri1sdj.sch.id
xn--9kqs4m6xlso8b.top
xn--n8js1r705itda293h4tluqoghug82d.com
xn--36q76bp3extuvxk9jaw50b260c.xn
6e1etlrrd016rxdnrgc1008.com
7wgl5i0rmju92k05.top
xn--80ahbccqtbd3bkoe3lqb.xn
xn--82-jlcuewcel4a.xn
lydnilqadojskkvfxa.top
kveoizo9hhuebhvy.top
mhz1y0fkj68q0n0.xyz
szsz1128zszs22.sbs
zg9tywlubmftzw5ldzqzmjc.com
xn--80aqecioa5a.xn
22451sw128thpl.com
xn----dtbjalgnq6abs7hl.xn
3c1b105f-1469-404e-8bc8-00195e2882b2.com
xn--oi2bw4qsvftpan61b.com
xn--1304bet10-r3b.com
xn--m8ss63f93j.top
ncjagxzshaeylchxy.com
2d884466-5bbb-4940-be19-0d14668c7f46.com
xn--64-glchp3abur.xn
xn----7sbbsltrcm5ac.xn
plkgutfqmiqa4tqs.cyou
4ha359p9n2cmc9g.xyz
xn--80ajwhiabl5a.xn
gd4y8dsuv3j3xb8.xyz
e943b6a5bda848b3.com
xn----8sbaavauwtgbanvogk0d4h.xn
e0b54b37b08f4e19.com
xn--2i0bm4p7vbgt999ev2cztk.com
350565d6cbf06a9c9f124d1ca65736e4.cfd
hukumdarmutfak.com
qhobhjpmqqomxe.com
z6wtz0xjzwzkgez8m6o9z7y7.xyz
xn--mgba3a4a8bphxr.com
okokbaidujiasu13.icu
xn--o39a02ldd36r4xdw9lita61hacc154j5c32lo29c6mobgbl7uvta.com
34001119dksezch618.top
amacvfrgbfnbcgmvhjmbj.com
84cbt0rjmk1qyzfneke7530.com
fmz3hqtvhazntpbr.top
```

**Comment by jarelllama** [comment]
After some testing, I able to make the threshold of detection more script to reduce false positives and lower the domain yield. Will continue testing to find the balance of detection and blocklist size.

**Comment by xRuffKez** [comment]
I can give you access to high Entropy nrd if you want for your project.

**Comment by jarelllama** [comment]
That would be nice! I appreciate the help.

**Comment by xRuffKez** [comment]
@jarelllama reach me on telegram my username:
![Screenshot_20241221_104419_Telegram](https://github.com/user-attachments/assets/9d99e5f2-4120-40ad-82fd-8ae43bd4cda8)

**Comment by xRuffKez** [comment]
@jarelllama 14 or 30 days?

**Comment by jarelllama** [comment]
I see your list is 67MB big 😅 . How do you process it into your phishing NRD list?

**Comment by xRuffKez** [comment]
> I see your list is 67MB big 😅 . How do you process it into your phishing NRD list?

Filtering out names like ```facebook facəbook faceb0ok``` etc

**Comment by jarelllama** [comment]
After decoding I see a lot (I shuffled 100 domains out) of phishing domains. My new source would be targeting DGA domains isntead. This is a sample of high confidence DGA domains:
```
fjmpt4vcgj.xyz
aaajdz.net.cn
99hhvghghjs99.com
xk4p0qvdj7t.top
jnhgw0677.com
f9k1z0d9j.biz
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com
520-psdtv14.top
www599992.com
cji372jxdk.top
hnxhdz.com.cn
vtdpbqvwgz.xyz
19d0jcw8k86p.cyou
cwg-hxwfc.com
s15q106aq.top
dhgfkjfhk.com
9smcp9ji7q.com
ejvjogvcm.com
60dcfc44d8760b05.com
gfhngcbfgd.xyz
hdhfvt2dqdwxduaz.cyou
qnjlqwc9.cyou
js46466zf9.top
pcfgfvcvxcd.com
8gmv3b60kfd35bhe.xyz
a5kvz-j1gq.xyz
wwwbg2244.com
9sj9z639x.com
4zj3h2xmk3t7bbcuw.xyz
uysxhvz1026.vip
ejm496ji1.top
sv368cpc2.com
2smx202409.cat
dfhb-3680.top
00f8c4bb25.com
yh33323xb78.top
js46466zf34.top
yy8556yy.cyou
yh33323xb82.top
703jwm301.top
34001126uvvpxxk107.top
sxr0jvy09.com
gcjxzlznw.com
tnqfxdp1440.vip
sd15q25zq.top
ykd256327.com
sg5156q41.top
lhhcv2q9uux.top
49294d7643b3.xyz
wuqrqgxxf3.blog
```

**Comment by jarelllama** [comment]
It seems like our lists target different things, which is a good thing since together our lists can cover more.

**Comment by xRuffKez** [comment]
Glad i can help 😊

**Comment by jarelllama** [comment]
@hagezi , I have tightened the threshold of detection and after filtering domains with english words and below 13 words, the domain yield is now 13691 domains (only for the first run). This source will only be used in the full version, not light.

Let me know if this would inflate the TIF list too much.

**Comment by jarelllama** [comment]
Another option is making it into a separate blocklist

**Comment by hagezi** [comment]
> Let me know if this would inflate the TIF list too much.

I can only answer briefly at the moment, I don't think that's a problem.  Do it ... ;)

Great work!

**Comment by jarelllama** [comment]
Tested and implemented. Thanks for the input.
